Repository FC-MINI-6/mini-project-FE, pull requests merged in 2023-08, with the labels that each got.

#19 [Feat] 홈 화면 일정 캘린더 UI 작업 반영
  package-lock.json
  package.json
  src/GlobalThemeConfig.ts
  src/components/calendar/CalendarHeader.tsx
  src/components/calendar/ScheduleCalendar.tsx
  src/components/calendar/ScheduleCard.tsx
  src/components/calendar/ScheduleList.tsx
  src/components/calendar/UserDropdown.tsx
  src/components/calendar/index.ts
  src/components/index.ts
  src/pages/App.tsx
  src/pages/Home.tsx
  src/pages/HomeCalendar.tsx
  src/pages/index.ts
  src/stores/index.ts
  src/stores/userListStore.ts
  src/stores/userSelectedStore.ts
  src/types/IUserSearchResponse.ts
  src/types/index.ts
  tsconfig.json
Labels: 작업 완료

#22 [Style] 휴가 페이지 목록 Table로 변경
  src/components/dayoff/DayOffHistoryItem.tsx
  src/components/dayoff/DayOffHistoryTable.tsx
  src/components/dayoff/DayOffRequestItem.tsx
  src/components/dayoff/DayOffRequestModal.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/components/dayoff/index.ts
  src/constants/dayOffTypes.ts
  src/constants/dummyData.ts
  src/constants/menuItems.ts
  src/pages/DayOff.tsx
  src/types/IDayOffResponse.ts
  src/types/index.ts
Labels: 작업 완료

#20 [Feat] 파일위치 수정, Login page 내 몇 가지 수정.
  src/components/index.ts
  src/components/login/index.ts
  src/components/signup/index.ts
  src/pages/App.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/pages/index.ts
Labels: 작업 완료

#28 [Feat] 휴가/당직 상태 처리에 따른 알림 푸시 기능
  index.html
  package-lock.json
  package.json
  public/logo.png
  src/components/admin/DutyMgt.tsx
  src/components/admin/ScheduleMgt.tsx
  src/components/common/AppNav.tsx
  src/components/common/NavLayout.tsx
  src/components/common/NotificationPopup.tsx
  src/components/common/index.ts
  src/firebase.ts
  src/types/INotificationData.ts
  src/types/index.ts
Labels: 작업 완료

#31 [Feat] 상태관리, 유효성 검사 추가
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
  src/stores/userStore.ts
Labels: 작업 완료

#32 [Feat] axios setting
  src/apis/authRequests.ts
  src/apis/axios.ts
  src/apis/index.ts
  src/apis/scheduleRequests.ts
  src/pages/HomeCalendar.tsx
  src/types/ICalendarUser.ts
  src/types/ICommonResponse.ts
  src/types/index.ts
Labels: 문서 추가

#37 [Feat] 휴가 신청 API 연동 반영
  src/apis/scheduleRequests.ts
  src/components/dayoff/DayOffRequestModal.tsx
  src/constants/index.ts
  src/constants/resultModalDatas.ts
  src/pages/App.tsx
  src/pages/DayOff.tsx
  src/stores/index.ts
  src/stores/modalStore.ts
  src/types/ICommonModal.ts
  src/types/IDayOffRequest.ts
  src/types/index.ts
Labels: 작업 완료

#38 [Feat] 휴가 신청/사용 내역 조회 및 휴가 사용 현황 데이터 연동 완료
  src/apis/scheduleRequests.ts
  src/components/common/SkeletonTable.tsx
  src/components/common/index.ts
  src/components/dayoff/DayOffHistoryTable.tsx
  src/components/dayoff/DayOffRequestModal.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/components/dayoff/DayOffSummary.tsx
  src/constants/resultModalDatas.ts
  src/pages/DayOff.tsx
  src/utils/calcNumOfDayOff.ts
  src/utils/filterUtils.ts
  src/utils/index.ts
Labels: 작업 완료

#42 [Fix] Enum 값 수정
  src/apis/dutyRequests.ts
  src/apis/scheduleRequests.ts
  src/components/dayoff/DayOffHistoryTable.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/components/duty/DutyRequestTable.tsx
  src/constants/menuItems.ts
  src/constants/status.ts
  src/types/dayoff/IDayOffResponse.ts
  src/utils/filterUtils.ts
Labels: 버그, 문서 추가

#43 [Feat] 휴가 취소 기능 반영
  src/apis/scheduleRequests.ts
  src/components/dayoff/DayOffRequestModal.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/constants/resultModalDatas.ts
  src/pages/App.tsx
  src/pages/DayOff.tsx
  src/utils/calcNumOfDayOff.ts
Labels: 작업 완료

#49 [Feat] 일정 캘린더 데이터 연동
  src/apis/scheduleRequests.ts
  src/components/calendar/ScheduleCalendar.tsx
  src/components/calendar/ScheduleCard.tsx
  src/components/calendar/ScheduleList.tsx
  src/components/calendar/UserDropdown.tsx
  src/components/dayoff/DayOffHistoryTable.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/constants/menuItems.ts
  src/constants/resultModalDatas.ts
  src/constants/status.ts
  src/pages/HomeCalendar.tsx
  src/stores/userListStore.ts
  src/stores/userSelectedStore.ts
  src/types/calendar/ICalendarDatas.ts
  src/types/calendar/ICalendarUser.ts
  src/types/calendar/index.ts
  src/types/index.ts
  src/utils/colorOfType.ts
  src/utils/filterUtils.ts
  src/utils/index.ts
Labels: 작업 완료

#51 [Feat] 휴가일수 조회 연동
  src/apis/scheduleRequests.ts
  src/pages/DayOff.tsx
  src/types/IUserSearchResponse.ts
  src/types/dayoff/IDayOffResponse.ts
  src/types/index.ts
Labels: 작업 완료

#53 [Fix] 스티일 및 key 오류 수정
  src/components/calendar/ScheduleList.tsx
  src/components/common/AppNav.tsx
  src/components/common/SkeletonTable.tsx
  src/components/dayoff/DayOffHistoryTable.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/components/duty/DutyHistoryTable.tsx
  src/components/duty/DutyRequestTable.tsx
Labels: 버그, 작업 완료

#54 feat: 관리자페이지 휴가/당직관리 API연동완료
  src/apis/adminScheduleRequests.ts
  src/apis/index.ts
  src/components/admin/DutyMgt.tsx
  src/components/admin/EmployeeMgt.tsx
  src/components/admin/ScheduleMgt.tsx
  src/stores/dayOffListStore.ts
  src/stores/dutyListStore.ts
  src/stores/index.ts
  src/types/admin/Schedule.ts
Labels: 작업 완료

#56 [Feat] navbar navigation 수정
  src/components/common/AppNav.tsx
  src/stores/index.ts
  src/stores/navTabStore.ts
Labels: 버그, 작업 완료

#58 [Feat] 토큰 관리 및 로그인 로그아웃 상태 관리
  package-lock.json
  package.json
  src/apis/adminEmployeeRequests.ts
  src/apis/adminScheduleRequests.ts
  src/apis/authRequests.ts
  src/apis/axios.ts
  src/apis/dutyRequests.ts
  src/apis/scheduleRequests.ts
  src/components/admin/DutyMgt.tsx
  src/components/common/AppNav.tsx
  src/components/common/NavLayout.tsx
  src/constants/resultModalDatas.ts
  src/hooks/index.ts
  src/hooks/useAxiosInterceptor.ts
  src/pages/App.tsx
  src/pages/HomeCalendar.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
  src/stores/dutyListStore.ts
  src/stores/index.ts
  src/stores/userStore.ts
  src/types/IUser.ts
  src/types/admin/Schedule.ts
  src/types/admin/index.ts
  src/types/index.ts
Labels: 작업 완료

#59 [Feat] 파이어베이스 알림 연동
  src/apis/adminScheduleRequests.ts
  src/components/admin/DutyMgt.tsx
  src/components/admin/ScheduleMgt.tsx
  src/components/common/AppNav.tsx
  src/components/common/NotificationPopup.tsx
  src/components/duty/DutyRequestTable.tsx
  src/stores/dayOffListStore.ts
  src/types/admin/Schedule.ts
Labels: 작업 완료

#62 fix: 스타일 수정
  src/components/admin/DutyMgt.tsx
  src/components/admin/EmployeeMgt.tsx
  src/components/admin/ScheduleMgt.tsx
  src/components/dayoff/DayOffHistoryTable.tsx
  src/components/dayoff/DayOffRequestTable.tsx
  src/components/duty/DutyHistoryTable.tsx
  src/components/duty/DutyRequestTable.tsx
  src/pages/Login.tsx
Labels: 버그, 작업 완료

#64 [Feat] 엑셀 다운로드
  package-lock.json
  package.json
  src/components/calendar/CalendarHeader.tsx
  src/components/calendar/ScheduleCalendar.tsx
  src/constants/excel.ts
  src/constants/index.ts
  src/types/common/IExcelData.ts
  src/types/common/index.ts
  src/utils/index.ts
  src/utils/parseExcelDatas.ts
Labels: 작업 완료

#61 [Feature] 로그인, 회원가입, 내정보 페이지 내 예외처리 기능.
  src/apis/index.ts
  src/constants/resultModalDatas.ts
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
Labels: 작업 완료

#65 [Fix] 타입스크립트 에러 수정
  src/utils/filterUtils.ts
Labels: 버그

#66 admin관련 파일 타입오류 수정
  src/apis/adminScheduleRequests.ts
  src/components/admin/DutyMgt.tsx
  src/components/admin/EmployeeMgt.tsx
  src/components/admin/ScheduleMgt.tsx
  src/stores/employeeListStore.ts
  src/types/admin/Employee.ts
  src/types/admin/EmployeeUpdate.ts
Labels: 버그, 작업 완료

#67 [Style] login page style 수정
  public/login_image.png
  src/components/login/styled.ts
  src/pages/Login.tsx
Labels: 작업 완료

#68 [Fix] 타입 에러 수정
  src/pages/Login.tsx
  src/pages/SignUp.tsx
Labels: 작업 완료

#73 docs: netlify.toml 추가
  .gitignore
  netlify.toml
Labels: 문서 추가

#76 [Style] 회원가입 스타일 수정
  public/signup_image.png
  public/signup_image2.png
  src/components/mypage/styled.ts
  src/components/signup/styled.ts
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
Labels: 작업 완료

#78 [Feat]회원가입 유효성검사 수정
  src/pages/SignUp.tsx
Labels: 작업 완료
